### ISSUE TITLE
Default centos install has permission error from cron

### ISSUE THREAD

**Issue by dbchelgit** [extremeshok/clamav-unofficial-sigs#186]
The default installation ends up sending this email error out:

Failed to restart clamd@scan.service: Interactive authentication required.
See system logs and 'systemctl status clamd@scan.service' for details.

Unsure on the best way to proceed; fresh clam itself runs as root and then drops privileges.  Something similar might need to happen here.

Suggestions?

**Comment by dbchelgit** [comment]
So, I fixed this - but a few changes required:

-  The centos7.conf file has a mistake in the reload command (clamd@scan instead of clamd.scan)
-  Commands should be changed to these instead:
`clamd_restart_opt="sudo systemctl restart clamd.scan"
clamd_reload_opt="sudo clamdscan --config-file=/etc/clamd.d/scan.conf --reload"
`
-  Needed to create a file in /etc/sudoers.d/95-clamav-unofficial-sigs with the following:
`#  Allow clamupdate to refresh clamd

clamupdate  ALL = NOPASSWD: /bin/systemctl restart clamd.scan
clamupdate  ALL = NOPASSWD: /bin/clamdscan --config-file=/etc/clamd.d/scan.conf --reload
`

This seems to fix the problem.

David.

**Comment by whataboutpereira** [comment]
The issue persists in 6.0.1.

/var/lib/clamav/dead.letter                                                                                                                                                                                        
Date: Sat, 3 Aug 2019 14:21:53 +0300 (EEST)
From: "(Cron Daemon)" <clamupdate>
To: clamupdate
Subject: Cron <clamupdate@orc> [ -x /usr/sbin/clamav-unofficial-sigs.sh ] && /usr/bin/bash /usr/sbin/clamav-unofficial-sigs.sh > /dev/null
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <LC_ALL=en_US.utf-8>
X-Cron-Env: <XDG_SESSION_ID=2528>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/996>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/var/lib/clamav>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=clamupdate>
X-Cron-Env: <USER=clamupdate>

Failed to restart clamd@scan.service: Interactive authentication required.
See system logs and 'systemctl status clamd@scan.service' for details.
---
This is on top of the fact that I haven't enabled clamd@scan at all on this system.

**Comment by whataboutpereira** [comment]
Also, if you noticed this failure e-mail ends up as a dead letter in clamupdate home directory. I would suggest adding MAILTO=root to the CentOS cron script.

**Comment by extremeshok** [comment]
Could you please push a PR with the fixes to the dev branch ?

**Comment by extremeshok** [comment]
in your user.conf, set the follow to prevent reload and restarts
reload_dbs="no"

**Comment by whataboutpereira** [comment]
Thanks! I had done that. Perhaps consider adding it to the centos specific defaults?

**Comment by extremeshok** [comment]
CentOS is a bit of a mess atm, considering how many methods and ways there are to install clamav, no standardized default configs, etc.

SELinux out of the box does not support clamav, the default clamav socket lacks permissions on boot. the standard clam@scan.service files bugs.

I will make a mention in the config to enable it.

**Comment by whataboutpereira** [comment]
The trouble here is that clamupdate has no permissions to run service restarts in any config (apart from allowing passwordless sudo as mentioned above).

**Comment by extremeshok** [comment]
Would you like to test the dev branch ? 
Im busy working on a clamav install guide for centos with the correct permissions

**Comment by whataboutpereira** [comment]
Just installed the dev version. I'll let you know how it behaves. :)

**Comment by whataboutpereira** [comment]
The dev script is using clamscan user for database updates. This however breaks freshclam updates, which defaults to clamupdate:clamupdate.

Cron <root@localhost> /usr/share/clamav/freshclam-sleep:
ERROR: Can't create temporary directory /var/lib/clamav/clamav-89762c9a11c97dc1add20976138019ea.tmp

I've reverted to clam_user="clamupdate" in user.conf

**Comment by extremeshok** [comment]
fixed #1ff6f8447184f66c7ee6e30a514fb9c43c407372

**Comment by extremeshok** [comment]
Any other issues ?

**Comment by whataboutpereira** [comment]
So far so good, apart from the hourly :) :
***********************************************************************************
ALERT: New version : v6.0.1 @ https://github.com/extremeshok/clamav-unofficial-sigs
***********************************************************************************
**************************************************************************************
ALERT: New configversion : v75 @ https://github.com/extremeshok/clamav-unofficial-sigs
**************************************************************************************

**Comment by extremeshok** [comment]
That is actually a bug, since u have higher versions ;P

So im going to sort that out

**Comment by whataboutpereira** [comment]
Thanks! :)

**Comment by whataboutpereira** [comment]
One more suggestion - after changing user the log file becomes unwriteable - maybe when the script is ran as root it could fix the log file owner as well. I spent a little time thinking there's something wrong with the script before I realized it can't write to the log. :)

**Comment by extremeshok** [comment]
who would the file owner need to be ?

**Comment by whataboutpereira** [comment]
Since it tries to write the log as clam_user/clam_group, then whatever is set in these. Just like it uses the clam_user when generating the cron script user.

**Comment by extremeshok** [comment]
> That is actually a bug, since u have higher versions ;P
> 
> So im going to sort that out

Fixed #238

**Comment by extremeshok** [comment]
closing. All fixes are done
